
const radiostations = [
        {
            id: "1",
            name: "DARDANIA RADIO",
            stream: "http://dardanialive.duckdns.org:8000/radio.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://i.ibb.co/s1Yj7ZX/DARDANIA-RADIO-STATION-LOGO-400-X400.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: true
        },   
        {
            id: "2",
            name: "Radio Viciana",
            stream: "http://viciana.no-ip.org:8010/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://www.radioviciana.com/Bilder/Radio%20Viciana%20%20new%20Kopie510.JPG",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: true
        },   
        {
            id: "3",
            name: "Radio Dukagjini",
            stream: "http://198.178.123.17:8824/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static-media.streema.com/media/cache/4e/e6/4ee66e9b889bd2d5e066698edab99dde.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: true
        },   
        {
            id: "4",
            name: "Dukagjini Shqip Radio",
            stream: "http://s2.voscast.com:8826/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static-media.streema.com/media/cache/4e/e6/4ee66e9b889bd2d5e066698edab99dde.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "5",
            name: "Dukagjini Love Radio",
            stream: "http://s2.voscast.com:8828/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static-media.streema.com/media/cache/4e/e6/4ee66e9b889bd2d5e066698edab99dde.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: true
        },   
        {
            id: "6",
            name: "Radio Dardania",
            stream: "http://radio.radiodardania.com:4000/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://mytuner.global.ssl.fastly.net/media/tvos_radios/Av8LzyHTxb.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: true
        },   
        {
            id: "7",
            name: "Radio Drenasi",
            stream: "http://ns5.albaservers.com:8010/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static-media.streema.com/media/cache/75/8a/758addc432c8f7f68af67d71ce3f259e.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "8",
            name: "Radio Dielli",
            stream: "http://212.24.109.1:8090/stream/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.winudf.com/v2/image/Y29tLnJhZGlvZGllbGxpLnJhZGlvX3NjcmVlbnNob3RzXzFfOWEwNTNjZmE/screen-1.jpg?fakeurl=1&type=.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "9",
            name: "Radio Marimonga",
            stream: "https://streaming.liveonline.radio/radio-marimanga",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://lh3.googleusercontent.com/1GQfRVlF5WQjDxIcqPAsM_gKk9zKx9uQPJiJrrR4APqRyUrYS8nQozqCJ1tqvSMJtw",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "10",
            name: "Radio Zhelina",
            stream: "http://server13.radiozhelina.com:8000",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static-media.streema.com/media/cache/af/51/af5138eba7805393ddc2d928de221262.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "11",
            name: "Radio Arta",
            stream: "http://173.192.207.51:8086/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2012/12/Radio-Arta-1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "12",
            name: "Radio Deqani",
            stream: "http://hyades.shoutca.st:8753/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/2/72502.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "13",
            name: "Radio Zeri Ilirides",
            stream: "http://109.123.116.202:8082/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://d3tahvfkle3xlm.cloudfront.net/images/nK4o/rH16Cnxa.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "14",
            name: "Radio Kosovarja",
            stream: "http://184.168.106.59:8000/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/12/Radio-Kosovarja.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "15",
            name: "Top Albnian Radio",
            stream: "https://streaming.liveonline.radio/top-albania-radio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static.tuneyou.com/images/logos/500_500/15/15/TopAlbaniaRadio100.0FM.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "16",
            name: "Radio Kosova e lire",
            stream: "http://188.165.192.5:8018/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.radiokosovaelire.com/wp-content/uploads/RKL_UCK-e1469806643318.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "17",
            name: "Radio Vala Rinore - Prishtina",
            stream: "http://84.22.46.10:8000/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://cdn6.aptoide.com/imgs/d/b/4/db48038f26efcb09061baac7adeb6680_screen.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "18",
            name: "Radio Shqip",
            stream: "http://198.178.123.5:8826/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://static-media.streema.com/media/cache/cc/2d/cc2d6f69aad696aa1942908c60b4278d.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "19",
            name: "Radio Kosova",
            stream: "http://82.114.72.2:8098/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://i.ytimg.com/vi/gv5vDU840l4/maxresdefault.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "20",
            name: "Radio Kosova 1",
            stream: "http://82.114.72.2:8088/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://static.radio.net/images/broadcasts/90/8c/13593/c175.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "21",
            name: "Radio NRG",
            stream: "http://ice31.securenetsystems.net/AL09.m3u",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://mytuner.global.ssl.fastly.net/media/tvos_radios/PK5zHskTtd.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "22",
            name: "Radio Emigranti",
            stream: "http://www.radioemigranti.com:8000/radio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/Radio-Emigranti.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "23",
            name: "VIP FM",
            stream: "https://streaming.liveonline.radio/radio-vip-fm",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://mytuner.global.ssl.fastly.net/media/tvos_radios/g373hfkq2mw3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "24",
            name: "VIP Albania",
            stream: "http://eu3.fastcast4u.com:5334/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://d2iw5las1rjvep.cloudfront.net/rfm/uploads/rlogo/300/300_1510344397.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "25",
            name: "Radio Llapi",
            stream: "http://radio.1dhe1.com:8555/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/Radio-Llapi.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "26",
            name: "Radio Tirana 1",
            stream: "https://streaming.liveonline.radio/radio-tirana",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://pbs.twimg.com/profile_images/448791002422063104/uOzX0w22.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "27",
            name: "Radio Tirana 2",
            stream: "https://streaming.liveonline.radio/radio-tirana-two",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://pbs.twimg.com/profile_images/448791002422063104/uOzX0w22.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "28",
            name: "Radio Tirana 3",
            stream: "https://streaming.liveonline.radio/radio-tirana-3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://pbs.twimg.com/profile_images/448791002422063104/uOzX0w22.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "29",
            name: "Radio Gurbeti",
            stream: "https://streaming.liveonline.radio/radio-gurbeti",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://i3.radionomy.com/radios/400/8123268d-7362-4923-8a24-da21b1d88cc1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "30",
            name: "Radio K4 90,2 FM - Prishtina",
            stream: "http://fm.radiokfor.com:8080/listen.pls",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://www.liveradio.ie/files/images/149568/radio_kfor.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "31",
            name: "RADIO K4 96.6 PRISHTINA/89.7",
            stream: "http://192.240.97.68:8090/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://www.liveradio.ie/files/images/149568/radio_kfor.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "32",
            name: "Radio Travel",
            stream: "http://93.190.141.15:7253/live",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/3/11263.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "33",
            name: "London Albanian Radio",
            stream: "http://192.111.140.6:8157/;stream.mp3/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://cdn.appshopper.com/icons/975/476277_larger.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "34",
            name: "Radio Kontakt 89.3",
            stream: "http://84.20.83.24:88/broadwavehigh.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/1/11231.v4.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "35",
            name: "Radio 1",
            stream: "http://80.90.87.67:88/broadwavehigh.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/1/11321.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "36",
            name: "Radio 4 Plus",
            stream: "http://74.221.215.47:8080/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/06/Radio-4-Plus.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "37",
            name: "Radio 7 Albania",
            stream: "http://93.190.141.15:7025/live",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/11/Radio-7-Albania.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "38",
            name: "Radio Ahireti",
            stream: "https://streaming.liveonline.radio/radio-ahireti",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://img1.radioforest.net/radio/753/753238/43723/slider-home.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "39",
            name: "Radio Alba",
            stream: "http://streaming.jusahost.com:9222/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/07/Radio-Alba.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "40",
            name: "Radio Deejay Fier",
            stream: "http://78.129.224.15/records/radiouser1785066/record.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/01/Radio-Deejay-Fier.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "41",
            name: "Radio Devolli",
            stream: "http://orion.shoutca.st:8028/radio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2015/04/Radio-Devolli.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "42",
            name: "Radio Eja",
            stream: "https://streaming.liveonline.radio/radio-eja",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/11/Radio-Eja.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "43",
            name: "Radio Emanuel",
            stream: "https://streaming.liveonline.radio/radio-emanuel",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/Radio-Emanuel.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "44",
            name: "Radio Fati",
            stream: "http://50.7.99.155:7234/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/11/Radio-Fati1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "45",
            name: "Radio Idea",
            stream: "http://5.133.182.174/records/radiouser2663645/record.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/radio-idea.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "46",
            name: "Radio Lezha",
            stream: "http://streaming.4-p.org:8132/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/03/Radio-Lezha1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "47",
            name: "Radio Logos Albania",
            stream: "http://s2.stationplaylist.com:9280/listen.aac",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/11/Radio-Logos-Albania.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "48",
            name: "Radio Mergimi",
            stream: "http://144.76.33.185:8000/;music.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/63507.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "49",
            name: "Radio Mergimtari",
            stream: "http://144.76.33.185:8000/;?1464712890393.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/Radio-Mergimtari.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "50",
            name: "Radio Nacional Albania",
            stream: "http://static-cdn1.ustream.tv/swf/live/viewerqos:33",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/03/Radio-Nacional-Albania.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "51",
            name: "Radio Pendimi",
            stream: "http://85.93.88.146:8014/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/Radio-Pendimi1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "52",
            name: "Radio Pulla",
            stream: "http://46.4.104.253:9986/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/11/Radio-Pulla.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "53",
            name: "Radio Select",
            stream: "http://mili.radioselect.net:10091/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/04/Radio-Select.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "54",
            name: "Radio Shqip",
            stream: "https://streaming.liveonline.radio/radio-shqip",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2012/12/Radio-Shqip.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "55",
            name: "Radio Spektrum 96.4 FM",
            stream: "https://streaming.liveonline.radio/radio-spektrum",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/3/11313.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "56",
            name: "Radio Sprint",
            stream: "http://panel8.newradio.it:9131/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/11/Radio-Sprint.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "57",
            name: "Radio Star 105.5 FM",
            stream: "http://listen.shoutcast.com/staralbania",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/11/Radio-Star-105.5-fm.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "58",
            name: "Radio Vicianum",
            stream: "https://streaming.liveonline.radio/radio-vicianum",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/Radio-Vicianum.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "59",
            name: "Studio Rejan",
            stream: "http://streaming.jusahost.com:9988/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/12/Studio-Rejan.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "60",
            name: "Tirana Jazz Radio",
            stream: "https://streaming.liveonline.radio/tirana-jazz-radio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/11/Tirana-Jazz-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "61",
            name: "Triple Radio",
            stream: "http://listen.radionomy.com/tripleradio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/12/Triple-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "62",
            name: "Voice of America",
            stream: "http://voa-28.akacast.akamaistream.net/7/54/322040/v1/ibb.akacast.akamaistream.net/voa-28",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/03/Voice-of-America-107.4.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "63",
            name: "Zeri Mitrovices",
            stream: "http://199.195.194.140:8021/stream",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/Zeri-Mitrovices-1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "64",
            name: "Radio Zeri",
            stream: "http://174.36.206.197:8038/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/3/72643.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "65",
            name: "Radio Jug",
            stream: "http://84.20.77.50:8000/listen.pls",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://static.radio.net/images/broadcasts/6a/40/17234/1/c175.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "66",
            name: "Radio DJ 96.1",
            stream: "http://95.107.173.168:6500/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/6/11196.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "67",
            name: "AMC Love Radio",
            stream: "http://80.78.76.171:6200/listen.pls?sid=1",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://cdn-radiotime-logos.tunein.com/s68420q.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "68",
            name: "Albanian Translation - Quran",
            stream: "http://184.173.185.71:9734/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/fblogo/4/12444.v4.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "69",
            name: "Radio Dashuria.AL Live ",
            stream: "https://streaming.liveonline.radio/radio-dashuria",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/fblogo/7/11307.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "70",
            name: "Radio Dashuria",
            stream: "http://184.168.106.59:8000/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/11307.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "71",
            name: "Albion FM",
            stream: "http://listen.radionomy.com/albion?type=.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/07/Albion-FM.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "72",
            name: "Alpo Radio",
            stream: "http://62.210.24.124:8379/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/11607.v5.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "73",
            name: "Audio Islam",
            stream: "http://listen.radioislam.org.za:8080/radioislam.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/09/Audio-Islam.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "74",
            name: "Boom Boom Radio",
            stream: "https://streaming.liveonline.radio/boom-boom-radio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/Boom-Boom-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "75",
            name: "Cmendina Radio",
            stream: "http://81.7.13.162:8000/cmendina?type=.mp3/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2015/04/Cmendina-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "76",
            name: "Heart Radio Islam",
            stream: "http://listen.radioislam.org.za:8080/radioislam.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/03/Heart-Radio-Islam.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "77",
            name: "Hit FM Online",
            stream: "http://hitfm.es.audio1.glb.ipercast.net:8000/hitfm.es/mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/Hit-FM-Online.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "78",
            name: "MCN Radio",
            stream: "http://81.7.13.162:8000/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/03/MCN-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "79",
            name: "Positive Gold 80s",
            stream: "http://vps563086.ovh.net:4000/;?1531864428813.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "80",
            name: "Positive Disco",
            stream: "https://streaming.liveonline.radio/positive-gold-disco",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "81",
            name: "Positive Gold 90s",
            stream: "http://vps563086.ovh.net:4020/;?1531852168546.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "82",
            name: "Positive Gold Alternative",
            stream: "http://vps563086.ovh.net:7060/;?1531865033372.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "83",
            name: "Positive Gold Balkan Express",
            stream: "http://balkan.positivegoldfm.net:4000/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "84",
            name: "Positive Gold Blues",
            stream: "http://vps563086.ovh.net:8010/;?1531864652967.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "85",
            name: "Positive Gold Ciftelia",
            stream: "https://streaming.liveonline.radio/positive-gold-ciftelia",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "86",
            name: "Positive Gold Cream",
            stream: "http://cream.positivegoldfm.net:5040/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "87",
            name: "Positive Gold Dance",
            stream: "http://dance.positivegoldfm.net:4060/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "88",
            name: "Positive Gold FM",
            stream: "https://streaming.liveonline.radio/positive-gold-fm",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "89",
            name: "Positive Gold Hip Hop",
            stream: "http://hiphop.positivegoldfm.net:4000/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "90",
            name: "Positive Gold Picimuli",
            stream: "https://streaming.liveonline.radio/positive-gold-picimuli",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "91",
            name: "Positive Gold Rock",
            stream: "http://rock.positivegoldfm.net:4080/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "92",
            name: "Positive Gold Smooth Jazz",
            stream: "https://streaming.liveonline.radio/positive-gold-smooth-jazz",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "93",
            name: "Positive Radio Thesari",
            stream: "http://vps563086.ovh.net:6020/;?1531866104103.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "94",
            name: "Positive Gold Turbo",
            stream: "http://vps563086.ovh.net:5080/;?1531865786209.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "95",
            name: "Positive Gold Urban",
            stream: "http://vps563086.ovh.net:5020/;?1531865105640.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "96",
            name: "Positive Hits",
            stream: "http://vps563086.ovh.net:6060/;?1531865870198.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "97",
            name: "Positive Love",
            stream: "https://streaming.liveonline.radio/positive-love",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://image.ibb.co/c2Pjxz/Positive.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "98",
            name: "Radio Rrapi",
            stream: "https://streaming.liveonline.radio/radio-rrapi",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/06/Radio-Rrapi.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "99",
            name: "Radio Vati",
            stream: "http://radiostream.neotel.mk:8000/radiovati?type=.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/06/Radio-Vati-88.4.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "100",
            name: "Radio Dibra Naqeta",
            stream: "http://184.154.185.170:8200/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://cdn.hipwallpaper.com/i/84/67/61Vsay.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "101",
            name: "Radio Peja",
            stream: "http://ns5.albaservers.com:8020/;?1516996701669.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/2/67202.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "102",
            name: "Radio Gjakova",
            stream: "http://37.26.69.30:8080/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/5/72565.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "103",
            name: "Radio Prizreni 88.4",
            stream: "http://s2.voscast.com:8828/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.freeradiotune.com/wp-content/uploads/2012/11/Radio-Prizreni-88.4.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "104",
            name: "Radio Ferizaji",
            stream: "http://live.rkoha.net:2015/;s.mp3/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/6/2286.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "105",
            name: "Radio Koha",
            stream: "http://perseus.shoutca.st:9504/stream",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/9/11199.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "106",
            name: "Radio Plus 102.2 FM",
            stream: "http://192.240.97.68:8090/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://i1.sndcdn.com/avatars-000002704712-hrqasp-t500x500.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "107",
            name: "Quran in Albanian",
            stream: "http://quraan.us:9996/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/11/Quran-Radio-Albanian.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "108",
            name: "Radio Svirca",
            stream: "http://stm43.srvstm.com:21554/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2015/07/Radio-Svirca.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "109",
            name: "Radio Evropa e Lirë",
            website: "",
            Frequency: "",
            location: "",
            description: "",stream_1: "",stream: 
            "http://rfe-channel-16.akacast.akamaistream.net/7/366/229666/v1/ibb.akacast.akamaistream.net/rfe_channel_16.mp3",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/12/Radio-Europe.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "110",
            name: "A Better Radio",
            stream: "http://listen.radionomy.com/a-better-70s-gold-hits-station?type=.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/12/ABetter-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "111",
            name: "Alba Radio",
            stream: "http://aradmin.ch:8000/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/alba-radio1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "112",
            name: "Alsion Radio",
            stream: "http://109.169.26.216:8018/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/Alsion-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "113",
            name: "AAB Radio",
            stream: "http://radio.aab-edu.net:8000/live.ogg",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/11/AAB-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "114",
            name: "City FM",
            stream: "http://stereo.wavestreamer.com:2872/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/02/City-FM.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "115",
            name: "Club FM 100.4",
            stream: "http://109.69.2.44:7500/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2011/06/Club-FM-100-4.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "116",
            name: "Radio ABC Korce",
            stream: "http://50.117.8.242:1716/Live?type=.mp3/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2015/04/Radio-ABC-Korce.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "117",
            name: "Kosovos Independence",
            stream: "http://richmedia.lse.ac.uk/publicLecturesAndEvents/20090218_1830_kosovosIndependenceOneYearOn.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/06/Kosovos-Independence.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "118",
            name: "Kronika Shqip",
            stream: "http://feedproxy.google.com/~r/albanian/~5/OKGUMX3hrr8/albanian_120911_232249.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/06/Kronika-Shqip.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "119",
            name: "LS Radio",
            stream: "http://live.lspublic.com:27022/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/09/LS-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "120",
            name: "Radio Alba Kline",
            stream: "http://iipptv.no-ip.org:8008/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/05/Radio-Alba-92.1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "121",
            name: "Radio Deshmia",
            stream: "https://streaming.liveonline.radio/radio-deshmia",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/12/Radio-Deshmia.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "122",
            name: "Radio Kosova 7",
            stream: "http://93.190.141.15:7032/live?type=.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/06/Radio-Kosova.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "123",
            name: "Radio Kosova Net",
            stream: "http://ns5.albaservers.com:8010/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/06/Radio-Kosova-Net.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "124",
            name: "Radio Shari Dragash",
            stream: "http://live.radio-sharri.info:8020/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/10/radio-sharri.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "125",
            name: "Radio Televizioni Iliria",
            stream: "https://streaming.liveonline.radio/radio-televizioni-iliria",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/05/Radio-Televizioni-Iliria.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "126",
            name: "Radio Xheti",
            stream: "http://178.32.62.154:9922/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/06/Radio-Xheti.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "127",
            name: "Radio Yjet",
            stream: "https://streaming.liveonline.radio/radio-yjet",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2016/10/Radio-Yjet.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "128",
            name: "Sa Vama K4",
            stream: "http://151.80.214.150:5080/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/06/Sa-Vama-K4.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "129",
            name: "Radio Fama Tetove",
            stream: "http://fama.radiofama.org:7000/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2014/12/Radio-Fama-Tetove-1.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "130",
            name: "Radio Rinora",
            stream: "http://streaming1-aphrodite.1000mikes.com/studio_rinora_wwwstudiorinoratk?encoding=mpeg?type=.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2015/11/Radio-Rinora.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "131",
            name: "Radio Sllatina",
            stream: "http://50.7.76.251:9300/",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/10/Radio-Sllatina.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "132",
            name: "Radio Maria",
            stream: "http://dreamsiteradiocp2.com:8028/;stream.nsv",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/1/11201.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "133",
            name: "Radio RTV21",
            stream: "http://84.22.44.247:1935/live/radio.stream/playlist.m3u8",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://upload.wikimedia.org/wikipedia/commons/4/4f/RTV_21_Logo.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "134",
            name: "Radio Lushnja",
            stream: "http://74.221.215.47:8000/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/4/11274.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "135",
            name: "Kiss Albania Radio",
            stream: "http://streamingv2.shoutcast.com/KissAlbaniaRadio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/65937.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "136",
            name: "Divan Radio",
            stream: "http://79.106.161.175:8000/stream",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/5/72485.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "137",
            name: "Radio Dedi24",
            stream: "http://radiodedi24.com:8000/;?.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/3/12413.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "138",
            name: "City Radio 88.0 FM",
            stream: "http://93.190.141.15:7368/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/6/11466.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "139",
            name: "Radio LIRIA",
            stream: "http://jusahost.com:9998/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/1/64881.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "140",
            name: "Radio Shqip",
            stream: "https://streaming.liveonline.radio/radio-shqip",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/3/69873.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "141",
            name: "Radio Myzeqeja",
            stream: "https://streaming.liveonline.radio/radio-myzeqeja",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/10777.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "142",
            name: "Radio Rainca",
            stream: "http://radiorainca.com:8000/;?.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/1/12441.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "143",
            name: "Radio Nostalgjia",
            stream: "http://janus.shoutca.st:8318/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://www.radionostalgjia.com/images/nostalgjia-logo.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "144",
            name: "Loti Vu Radio",
            stream: "http://84.20.83.24:8000/broadwave.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/1/73021.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "145",
            name: "Radio Hasi Thate",
            stream: "http://listen.lspublic.com:8000/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/6/72566.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "146",
            name: "Albtimes Radio",
            stream: "https://streaming.liveonline.radio/albtimes-radio",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/72427.v4.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "147",
            name: "Radio Shipkovica",
            stream: "http://orion.shoutca.st:8625/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/9/72639.v3.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "148",
            name: "Radio Udhëzimi",
            stream: "http://46.4.104.253:9998/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/0/72640.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "149",
            name: "Radio Lindja",
            stream: "http://213.239.218.99:7108/;stream.mp3",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/5/12445.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "150",
            name: "Radio Ngjallja",
            stream: "http://149.202.214.27:8888/radiongjallja",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/5/72405.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "151",
            name: "Radio INFinit",
            stream: "http://streaming.radionomy.com/INFinit-RADIO",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/2/11252.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "152",
            name: "Burimi Jetes",
            stream: "http://46.4.104.253:9996/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/8/12268.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "153",
            name: "Radio Kanali Shqip",
            stream: "http://64.150.176.42:8178/stream",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/8/72628.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "154",
            name: "Blue Mari Radio",
            stream: "http://s1.wohooo.net:9648/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/70067.v5.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "155",
            name: "Top Gold",
            stream: "http://live.topgold.al:9080/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "http://www.liveonlineradio.net/wp-content/uploads/2013/11/Top-Gold-Radio.jpg",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "156",
            name: "Alfa e Omega Radio",
            stream: "http://cp11.shoutcheap.com:8037/;",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/0/11230.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "157",
            name: "Divan Lounge",
            stream: "http://play.divanradio.com:8000/lounge",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/2/73092.v4.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "158",
            name: "Divan Gold",
            stream: "http://play.divanradio.com:8000/gold",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/3/73093.v5.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "159",
            name: "Divan House",
            stream: "http://play.divanradio.com:8000/house",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/7/73107.v1.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },   
        {
            id: "160",
            name: "Divan Jazz",
            stream: "http://play.divanradio.com:8000/jazz",
            stream_1: "",
            website: "",
            Frequency: "",
            location: "",
            description: "",
            icon: "https://us0-cdn.onlineradiobox.com/img/logo/2/73162.v2.png",
            language: "English",
            genre: "Entertainment, News, Music, Politics, Sports, Variety",
            popular: false
        },

]
export default radiostations;
        